name: Build  Android CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: '%compiler% -dumpmachine; %compiler% -dumpversion'
      CCACHE_NOHASHDIR: 'true'
      CCACHE_HARDLINK: 'true'
      CCACHE_BASEDIR: '${{ github.workspace }}'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      continue-on-error: true
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Write key
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
      run: |
        if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
          echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
          echo androidKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
          echo androidKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
          echo androidStoreFile='key.jks' >> gradle.properties
          echo ${{ secrets.KEY_STORE }} | base64 --decode > key.jks
        fi

    - name: Checkout libxposed/api
      uses: actions/checkout@main
      with:
        repository: libxposed/api
        path: libxposed/api
        ref: 54582730315ba4a3d7cfaf9baf9d23c419e07006

    - name: Checkout libxposed/service
      uses: actions/checkout@main
      with:
        repository: libxposed/service
        path: libxposed/service

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup ninja
      uses: seanmiddleditch/gha-setup-ninja@master
      with:
        version: 1.12.0

    - name: Remove Android's cmake
      shell: bash
      run: rm -rf $ANDROID_HOME/cmake

    - name: Build local dependencies
      run: |
        echo "--- Building API dependency ---"
        cd libxposed/api
        ./gradlew :api:publishApiPublicationToMavenLocal
        echo "--- Building Service Interface dependency ---"
        cd ../service
        ./gradlew :interface:publishInterfacePublicationToMavenLocal

    - name: Set short commit id
      run: echo "commit=$(echo ${{ github.sha }} | cut -c-7)" > $GITHUB_ENV

    - name: Build with Gradle
      run: |
        echo 'org.gradle.parallel=true' >> gradle.properties
        echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
        echo 'android.native.buildOutput=verbose' >> gradle.properties
        ./gradlew buildAll

    - name: Upload Debug artifact
      uses: actions/upload-artifact@v4
      with:
          name: lspatch-debug
          path: out/debug/*

    - name: Upload Release artifact
      uses: actions/upload-artifact@v4
      with:
          name: lspatch-release
          path: out/release/*

    - name: Upload mappings
      uses: actions/upload-artifact@v4
      with:
          name: mappings
          path: |
              patch-loader/build/outputs/mapping
              manager/build/outputs/mapping

    - name: Upload symbols
      uses: actions/upload-artifact@v4
      with:
          name: symbols
          path: |
              patch-loader/build/symbols
